trigger:
  branches:
    include:
      - main

jobs:
- job: Deploy
  displayName: 'Deploy to EKS with ArgoCD'
  pool:
    vmImage: 'ubuntu-latest'  # Ou use um agente auto-hospedado

  steps:


  - script: |
      # Instalando o AWS CLI
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install --update
    displayName: 'Install AWS CLI'

  - script: |
      # Configurar o AWS CLI com as credenciais
      aws configure set aws_access_key_id $(DEVOPS_ACESS_KEY)
      aws configure set aws_secret_access_key $(DEVOPS_SECRET_KEY)
      aws configure set region us-east-1  # Substitua pela sua região
    displayName: 'Configure AWS CLI'

  - script: |
      aws eks --region us-east-1 update-kubeconfig --name devops
    displayName: 'Configure kubectl for EKS'

  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'

  - script: |
      helm repo add argo https://argoproj.github.io/argo-helm
      helm repo update
    displayName: 'Add ArgoCD Helm repo'

  - script: |
      kubectl config current-context
      helm install argocd argo/argo-cd --namespace argocd --create-namespace
    displayName: 'Install ArgoCD using Helm'

  - script: |
      kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd
    displayName: 'Wait for ArgoCD pods to be ready'

  - script: |
      kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
    displayName: 'Get ArgoCD admin password'
