name: Install ArgoCD on EKS

on:
  push:
    branches:
      - main  
    paths:
      - .github/workflows/argocd-eks.yml  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Configuração das credenciais da AWS
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      # 3. Configurar kubectl para EKS
      - name: Configure kubectl for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      # 4. Instalar o Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version --short  # Verifica a versão do Helm instalada

      # 5. Adicionar o repositório do ArgoCD no Helm
      - name: Add ArgoCD Helm repository
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      # 6. Instalar o ArgoCD no EKS
      - name: Install ArgoCD on EKS
        run: |
          helm install argocd argo/argo-cd --namespace argocd --create-namespace
          
      # 7. (Opcional) Espera para o ArgoCD estar totalmente implantado
      - name: Wait for ArgoCD to be deployed
        run: |
          kubectl rollout status deployment/argocd-server -n argocd --timeout=600s