name: ArgoCD_Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Usa o runner no seu WSL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Minikube is running
        run: |
          sudo apt update && sudo apt install -y unzip curl
          minikube start --driver=docker --force
          export KUBECONFIG=$(minikube kubeconfig)

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add ArgoCD Helm repo
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Install ArgoCD using Helm
        run: |
          helm install argocd argo/argo-cd --namespace argocd --create-namespace

      - name: Wait for ArgoCD pods to be ready
        run: |
          echo "Aguardando os pods do ArgoCD iniciarem..."
          kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd || \
          (echo "Tempo esgotado! Listando os pods para debugging:" && kubectl get pods -n argocd && exit 1)

      - name: Get ArgoCD admin password
        run: |
          kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
